name: Publish to Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      
      - run: gpg --version
      
      - run: gpg --list-secret-keys --keyid-format=long
      
      - run: cat ~/.m2/settings.xml
     
      - run: mvn -B -ntp deploy -P gpg,!mut -f engine/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_NAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_PASS }}
